export const urls = {
    PRODUCTS: 'termekek',
    PRODUCT: 'termek',
    USERS: 'felhasznalok',
    USER: 'felhasznalo',
    LOGIN: 'bejelentkezes',
    REGIST: 'regisztracio',
    NOT_FOUND: '404',
    GAMES: 'jatekok',
    GAME: 'jatek',
    DECKS: 'decks',
    DECK: 'deck',
    USER_DETAIL: 'felhasznalo-adatok',
    PRODUCT_DETAIL: 'termek-adatok',
  };